version: '3.9'

services:

  mysql_rhhab:
    image: mariadb:10.7
    container_name: rhhmariadb
    hostname: mariadb
    env_file: ./docker/mariadb/.env
    ports:
      - "3311:3306"
    volumes:
      - ./database/rhhabitation.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - wsh-network

  wshabitation:
    build:
      context: .
      dockerfile: DockerfileForCompose
    container_name: wshabitation
    ports:
      - "8011:8080"
    volumes:
      - ./logs:/logs
    networks:
      - wsh-network

networks:
  wsh-network:
    driver: bridge
